services:
  fact_api:
    image: fact-api
    build: fact_api/.
    ports:
      - 8000:80
  print_facts:
    image: print-facts
    environment:
      - BASE_URL=http://fact_api
    build: print_facts/.